# Makefile.in generated by automake 1.10 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/samtools
pkglibdir = $(libdir)/samtools
pkgincludedir = $(includedir)/samtools
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i386-apple-darwin11.3.0
host_triplet = i386-apple-darwin11.3.0
bin_PROGRAMS = samtools$(EXEEXT) bcftools$(EXEEXT) razip$(EXEEXT) \
	bgzip$(EXEEXT) pbgzip$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(dist_doc_DATA) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(srcdir)/config.h.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS config/compile config/config.guess \
	config/config.sub config/depcomp config/install-sh \
	config/ltmain.sh config/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(docdir)"
libLIBRARIES_INSTALL = $(INSTALL_DATA)
LIBRARIES = $(lib_LIBRARIES)
ARFLAGS = cru
libbam_a_AR = $(AR) $(ARFLAGS)
libbam_a_LIBADD =
am__objects_1 = bgzf.$(OBJEXT)
am__dirstamp = $(am__leading_dot)dirstamp
am__objects_2 = pbgzip_src/block.$(OBJEXT) \
	pbgzip_src/consumer.$(OBJEXT) pbgzip_src/pbgzf.$(OBJEXT) \
	pbgzip_src/queue.$(OBJEXT) pbgzip_src/reader.$(OBJEXT) \
	pbgzip_src/util.$(OBJEXT) pbgzip_src/writer.$(OBJEXT)
am__objects_3 = knetfile.$(OBJEXT)
am__objects_4 = razf.$(OBJEXT)
am__objects_5 = $(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) kstring.$(OBJEXT) bam_aux.$(OBJEXT) \
	bam.$(OBJEXT) bam_import.$(OBJEXT) sam.$(OBJEXT) \
	bam_index.$(OBJEXT) bam_pileup.$(OBJEXT) bam_lpileup.$(OBJEXT) \
	bam_md.$(OBJEXT) faidx.$(OBJEXT) bedidx.$(OBJEXT) \
	bam_sort.$(OBJEXT) sam_header.$(OBJEXT) bam_reheader.$(OBJEXT) \
	kprobaln.$(OBJEXT) bam_cat.$(OBJEXT)
am_libbam_a_OBJECTS = $(am__objects_5)
libbam_a_OBJECTS = $(am_libbam_a_OBJECTS)
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am__objects_6 = bcftools_src/bcf.$(OBJEXT) \
	bcftools_src/bcf2qcall.$(OBJEXT) \
	bcftools_src/bcfutils.$(OBJEXT) bcftools_src/call1.$(OBJEXT) \
	bcftools_src/em.$(OBJEXT) bcftools_src/fet.$(OBJEXT) \
	bcftools_src/index.$(OBJEXT) bcftools_src/kfunc.$(OBJEXT) \
	bcftools_src/kmin.$(OBJEXT) bcftools_src/mut.$(OBJEXT) \
	bcftools_src/prob1.$(OBJEXT) bcftools_src/vcf.$(OBJEXT)
am_bcftools_OBJECTS = $(am__objects_5) $(am__objects_6) \
	bcftools_src/main.$(OBJEXT)
bcftools_OBJECTS = $(am_bcftools_OBJECTS)
bcftools_DEPENDENCIES =
am_bgzip_OBJECTS = $(am__objects_3) $(am__objects_1) bgzip.$(OBJEXT)
bgzip_OBJECTS = $(am_bgzip_OBJECTS)
bgzip_DEPENDENCIES =
am_pbgzip_OBJECTS = $(am__objects_1) $(am__objects_2) $(am__objects_3) \
	pbgzip_src/pbgzip.$(OBJEXT)
pbgzip_OBJECTS = $(am_pbgzip_OBJECTS)
pbgzip_DEPENDENCIES =
am_razip_OBJECTS = $(am__objects_3) $(am__objects_4) razip.$(OBJEXT)
razip_OBJECTS = $(am_razip_OBJECTS)
razip_DEPENDENCIES =
am_samtools_OBJECTS = $(am__objects_5) $(am__objects_6) \
	bam2bcf.$(OBJEXT) bam2bcf_indel.$(OBJEXT) bam2depth.$(OBJEXT) \
	bam_color.$(OBJEXT) bam_mate.$(OBJEXT) bam_plcmd.$(OBJEXT) \
	bam_qa.$(OBJEXT) bam_rmdup.$(OBJEXT) bam_rmdupse.$(OBJEXT) \
	bam_stat.$(OBJEXT) bam_tview.$(OBJEXT) bamtk.$(OBJEXT) \
	cut_target.$(OBJEXT) errmod.$(OBJEXT) kaln.$(OBJEXT) \
	padding.$(OBJEXT) phase.$(OBJEXT) sam_view.$(OBJEXT) \
	sample.$(OBJEXT)
samtools_OBJECTS = $(am_samtools_OBJECTS)
samtools_DEPENDENCIES =
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libbam_a_SOURCES) $(bcftools_SOURCES) $(bgzip_SOURCES) \
	$(pbgzip_SOURCES) $(razip_SOURCES) $(samtools_SOURCES)
DIST_SOURCES = $(libbam_a_SOURCES) $(bcftools_SOURCES) \
	$(bgzip_SOURCES) $(pbgzip_SOURCES) $(razip_SOURCES) \
	$(samtools_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
dist_docDATA_INSTALL = $(INSTALL_DATA)
DATA = $(dist_doc_DATA)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/nhomer/git/samtools/config/missing --run aclocal-1.10
ALLOCA = 
AMTAR = ${SHELL} /Users/nhomer/git/samtools/config/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /Users/nhomer/git/samtools/config/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/nhomer/git/samtools/config/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/nhomer/git/samtools/config/missing --run automake-1.10
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -g -Wall -O2 -pthread -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = dsymutil
DUMPBIN = 
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld
LDFLAGS = 
LIBOBJS =  ${LIBOBJDIR}lstat$U.o
LIBS = -lpthread -lm -lz  -lncurses
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = lipo
LN_S = ln -s
LTLIBOBJS =  ${LIBOBJDIR}lstat$U.lo
MAKEINFO = ${SHELL} /Users/nhomer/git/samtools/config/missing --run makeinfo
MKDIR_P = config/install-sh -c -d
NM = /usr/bin/nm
NMEDIT = nmedit
OBJDUMP = false
OBJEXT = o
OTOOL = otool
OTOOL64 = :
PACKAGE = samtools
PACKAGE_BUGREPORT = samtools-help@lists.sourceforge.net
PACKAGE_NAME = samtools
PACKAGE_STRING = samtools 0.1.18
PACKAGE_TARNAME = samtools
PACKAGE_VERSION = 0.1.18
PATH_SEPARATOR = :
POW_LIB = 
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.1.18
abs_builddir = /Users/nhomer/git/samtools
abs_srcdir = /Users/nhomer/git/samtools
abs_top_builddir = /Users/nhomer/git/samtools
abs_top_srcdir = /Users/nhomer/git/samtools
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i386-apple-darwin11.3.0
build_alias = 
build_cpu = i386
build_os = darwin11.3.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datadir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i386-apple-darwin11.3.0
host_alias = 
host_cpu = i386
host_os = darwin11.3.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /Users/nhomer/git/samtools/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/config/install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_builddir = .
top_srcdir = .
lib_LIBRARIES = libbam.a
BGZF_SOURCES = \
			   bgzf.c bgzf.h 

PBGZF_SOURCES = \
				pbgzip_src/block.c pbgzip_src/block.h \
				pbgzip_src/consumer.c pbgzip_src/consumer.h \
				pbgzip_src/pbgzf.c pbgzip_src/pbgzf.h \
				pbgzip_src/queue.c pbgzip_src/queue.h \
				pbgzip_src/reader.c pbgzip_src/reader.h \
				pbgzip_src/util.c pbgzip_src/util.h \
				pbgzip_src/writer.c pbgzip_src/writer.h 

RAZF_SOURCES = \
			   razf.c razf.h 

KNETFILE_SOURCES = \
				   knetfile.c knetfile.h 

LIBRARY_SOURCES = \
				  ${BGZF_SOURCES} \
				  ${PBGZF_SOURCES} \
				  ${KNETFILE_SOURCES} \
				  ${RAZF_SOURCES} \
				  kstring.c kstring.h \
				  bam_aux.c \
				  bam.c bam.h \
				  bam_import.c \
				  sam.c sam.h \
				  bam_index.c \
				  bam_pileup.c \
				  bam_lpileup.c \
				  bam_md.c \
				  faidx.c faidx.h \
				  bedidx.c \
				  bam_sort.c \
				  sam_header.c sam_header.h \
				  bam_reheader.c \
				  kprobaln.c kprobaln.h \
				  bam_cat.c 

BCFTOOLS_SOURCES = \
				   bcftools_src/bcf.c bcftools_src/bcf.h \
				   bcftools_src/bcf2qcall.c \
				   bcftools_src/bcfutils.c \
				   bcftools_src/call1.c \
				   bcftools_src/em.c \
				   bcftools_src/fet.c \
				   bcftools_src/index.c \
				   bcftools_src/kfunc.c \
				   bcftools_src/kmin.c \
				   bcftools_src/kmin.h \
				   bcftools_src/mut.c \
				   bcftools_src/prob1.c \
				   bcftools_src/prob1.h \
				   bcftools_src/vcf.c

samtools_SOURCES = \
				   ${LIBRARY_SOURCES} \
				   ${BCFTOOLS_SOURCES} \
				   bam2bcf.c bam2bcf.h \
				   bam2bcf_indel.c bam2depth.c \
				   bam_color.c bam_endian.h \
				   bam_mate.c \
				   bam_plcmd.c bam_qa.c \
				   bam_rmdup.c bam_rmdupse.c \
				   bam_stat.c bam_tview.c bamtk.c \
				   cut_target.c errmod.c errmod.h \
				   kaln.c kaln.h \
				   khash.h \
				   klist.h \
				   kseq.h \
				   ksort.h \
				   padding.c phase.c radix.h \
				   sam_view.c sample.c sample.h

samtools_LDADD = 
bcftools_SOURCES = \
				   ${LIBRARY_SOURCES} \
				   ${BCFTOOLS_SOURCES} \
				   bcftools_src/main.c

bcftools_LDADD = 
razip_SOURCES = \
				${KNETFILE_SOURCES} \
				${RAZF_SOURCES} \
				razip.c

razip_LDADD = 
bgzip_SOURCES = \
				${KNETFILE_SOURCES} \
				${BGZF_SOURCES} \
				bgzip.c

bgzip_LDADD = 
pbgzip_SOURCES = \
				 ${BGZF_SOURCES} \
				 ${PBGZF_SOURCES} \
				 ${KNETFILE_SOURCES} \
				 pbgzip_src/pbgzip.c

pbgzip_LDADD = 
libbam_a_SOURCES = \
				   ${LIBRARY_SOURCES}

EXTRA_DIST = LICENSE \
			 autogen.sh \
			 samtools.git.rev \
			 samtools.1

SUBDIRS = . 
dist_doc_DATA = LICENSE samtools.1
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-libLIBRARIES: $(lib_LIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(libLIBRARIES_INSTALL) '$$p' '$(DESTDIR)$(libdir)/$$f'"; \
	    $(libLIBRARIES_INSTALL) "$$p" "$(DESTDIR)$(libdir)/$$f"; \
	  else :; fi; \
	done
	@$(POST_INSTALL)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    p=$(am__strip_dir) \
	    echo " $(RANLIB) '$(DESTDIR)$(libdir)/$$p'"; \
	    $(RANLIB) "$(DESTDIR)$(libdir)/$$p"; \
	  else :; fi; \
	done

uninstall-libLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(libdir)/$$p'"; \
	  rm -f "$(DESTDIR)$(libdir)/$$p"; \
	done

clean-libLIBRARIES:
	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)
pbgzip_src/$(am__dirstamp):
	@$(MKDIR_P) pbgzip_src
	@: > pbgzip_src/$(am__dirstamp)
pbgzip_src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) pbgzip_src/$(DEPDIR)
	@: > pbgzip_src/$(DEPDIR)/$(am__dirstamp)
pbgzip_src/block.$(OBJEXT): pbgzip_src/$(am__dirstamp) \
	pbgzip_src/$(DEPDIR)/$(am__dirstamp)
pbgzip_src/consumer.$(OBJEXT): pbgzip_src/$(am__dirstamp) \
	pbgzip_src/$(DEPDIR)/$(am__dirstamp)
pbgzip_src/pbgzf.$(OBJEXT): pbgzip_src/$(am__dirstamp) \
	pbgzip_src/$(DEPDIR)/$(am__dirstamp)
pbgzip_src/queue.$(OBJEXT): pbgzip_src/$(am__dirstamp) \
	pbgzip_src/$(DEPDIR)/$(am__dirstamp)
pbgzip_src/reader.$(OBJEXT): pbgzip_src/$(am__dirstamp) \
	pbgzip_src/$(DEPDIR)/$(am__dirstamp)
pbgzip_src/util.$(OBJEXT): pbgzip_src/$(am__dirstamp) \
	pbgzip_src/$(DEPDIR)/$(am__dirstamp)
pbgzip_src/writer.$(OBJEXT): pbgzip_src/$(am__dirstamp) \
	pbgzip_src/$(DEPDIR)/$(am__dirstamp)
libbam.a: $(libbam_a_OBJECTS) $(libbam_a_DEPENDENCIES) 
	-rm -f libbam.a
	$(libbam_a_AR) libbam.a $(libbam_a_OBJECTS) $(libbam_a_LIBADD)
	$(RANLIB) libbam.a
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
bcftools_src/$(am__dirstamp):
	@$(MKDIR_P) bcftools_src
	@: > bcftools_src/$(am__dirstamp)
bcftools_src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) bcftools_src/$(DEPDIR)
	@: > bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/bcf.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/bcf2qcall.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/bcfutils.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/call1.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/em.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/fet.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/index.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/kfunc.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/kmin.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/mut.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/prob1.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/vcf.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools_src/main.$(OBJEXT): bcftools_src/$(am__dirstamp) \
	bcftools_src/$(DEPDIR)/$(am__dirstamp)
bcftools$(EXEEXT): $(bcftools_OBJECTS) $(bcftools_DEPENDENCIES) 
	@rm -f bcftools$(EXEEXT)
	$(LINK) $(bcftools_OBJECTS) $(bcftools_LDADD) $(LIBS)
bgzip$(EXEEXT): $(bgzip_OBJECTS) $(bgzip_DEPENDENCIES) 
	@rm -f bgzip$(EXEEXT)
	$(LINK) $(bgzip_OBJECTS) $(bgzip_LDADD) $(LIBS)
pbgzip_src/pbgzip.$(OBJEXT): pbgzip_src/$(am__dirstamp) \
	pbgzip_src/$(DEPDIR)/$(am__dirstamp)
pbgzip$(EXEEXT): $(pbgzip_OBJECTS) $(pbgzip_DEPENDENCIES) 
	@rm -f pbgzip$(EXEEXT)
	$(LINK) $(pbgzip_OBJECTS) $(pbgzip_LDADD) $(LIBS)
razip$(EXEEXT): $(razip_OBJECTS) $(razip_DEPENDENCIES) 
	@rm -f razip$(EXEEXT)
	$(LINK) $(razip_OBJECTS) $(razip_LDADD) $(LIBS)
samtools$(EXEEXT): $(samtools_OBJECTS) $(samtools_DEPENDENCIES) 
	@rm -f samtools$(EXEEXT)
	$(LINK) $(samtools_OBJECTS) $(samtools_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f bcftools_src/bcf.$(OBJEXT)
	-rm -f bcftools_src/bcf2qcall.$(OBJEXT)
	-rm -f bcftools_src/bcfutils.$(OBJEXT)
	-rm -f bcftools_src/call1.$(OBJEXT)
	-rm -f bcftools_src/em.$(OBJEXT)
	-rm -f bcftools_src/fet.$(OBJEXT)
	-rm -f bcftools_src/index.$(OBJEXT)
	-rm -f bcftools_src/kfunc.$(OBJEXT)
	-rm -f bcftools_src/kmin.$(OBJEXT)
	-rm -f bcftools_src/main.$(OBJEXT)
	-rm -f bcftools_src/mut.$(OBJEXT)
	-rm -f bcftools_src/prob1.$(OBJEXT)
	-rm -f bcftools_src/vcf.$(OBJEXT)
	-rm -f pbgzip_src/block.$(OBJEXT)
	-rm -f pbgzip_src/consumer.$(OBJEXT)
	-rm -f pbgzip_src/pbgzf.$(OBJEXT)
	-rm -f pbgzip_src/pbgzip.$(OBJEXT)
	-rm -f pbgzip_src/queue.$(OBJEXT)
	-rm -f pbgzip_src/reader.$(OBJEXT)
	-rm -f pbgzip_src/util.$(OBJEXT)
	-rm -f pbgzip_src/writer.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/bam.Po
include ./$(DEPDIR)/bam2bcf.Po
include ./$(DEPDIR)/bam2bcf_indel.Po
include ./$(DEPDIR)/bam2depth.Po
include ./$(DEPDIR)/bam_aux.Po
include ./$(DEPDIR)/bam_cat.Po
include ./$(DEPDIR)/bam_color.Po
include ./$(DEPDIR)/bam_import.Po
include ./$(DEPDIR)/bam_index.Po
include ./$(DEPDIR)/bam_lpileup.Po
include ./$(DEPDIR)/bam_mate.Po
include ./$(DEPDIR)/bam_md.Po
include ./$(DEPDIR)/bam_pileup.Po
include ./$(DEPDIR)/bam_plcmd.Po
include ./$(DEPDIR)/bam_qa.Po
include ./$(DEPDIR)/bam_reheader.Po
include ./$(DEPDIR)/bam_rmdup.Po
include ./$(DEPDIR)/bam_rmdupse.Po
include ./$(DEPDIR)/bam_sort.Po
include ./$(DEPDIR)/bam_stat.Po
include ./$(DEPDIR)/bam_tview.Po
include ./$(DEPDIR)/bamtk.Po
include ./$(DEPDIR)/bedidx.Po
include ./$(DEPDIR)/bgzf.Po
include ./$(DEPDIR)/bgzip.Po
include ./$(DEPDIR)/cut_target.Po
include ./$(DEPDIR)/errmod.Po
include ./$(DEPDIR)/faidx.Po
include ./$(DEPDIR)/kaln.Po
include ./$(DEPDIR)/knetfile.Po
include ./$(DEPDIR)/kprobaln.Po
include ./$(DEPDIR)/kstring.Po
include ./$(DEPDIR)/padding.Po
include ./$(DEPDIR)/phase.Po
include ./$(DEPDIR)/razf.Po
include ./$(DEPDIR)/razip.Po
include ./$(DEPDIR)/sam.Po
include ./$(DEPDIR)/sam_header.Po
include ./$(DEPDIR)/sam_view.Po
include ./$(DEPDIR)/sample.Po
include bcftools_src/$(DEPDIR)/bcf.Po
include bcftools_src/$(DEPDIR)/bcf2qcall.Po
include bcftools_src/$(DEPDIR)/bcfutils.Po
include bcftools_src/$(DEPDIR)/call1.Po
include bcftools_src/$(DEPDIR)/em.Po
include bcftools_src/$(DEPDIR)/fet.Po
include bcftools_src/$(DEPDIR)/index.Po
include bcftools_src/$(DEPDIR)/kfunc.Po
include bcftools_src/$(DEPDIR)/kmin.Po
include bcftools_src/$(DEPDIR)/main.Po
include bcftools_src/$(DEPDIR)/mut.Po
include bcftools_src/$(DEPDIR)/prob1.Po
include bcftools_src/$(DEPDIR)/vcf.Po
include pbgzip_src/$(DEPDIR)/block.Po
include pbgzip_src/$(DEPDIR)/consumer.Po
include pbgzip_src/$(DEPDIR)/pbgzf.Po
include pbgzip_src/$(DEPDIR)/pbgzip.Po
include pbgzip_src/$(DEPDIR)/queue.Po
include pbgzip_src/$(DEPDIR)/reader.Po
include pbgzip_src/$(DEPDIR)/util.Po
include pbgzip_src/$(DEPDIR)/writer.Po

.c.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	mv -f $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ $<

.c.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	mv -f $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	mv -f $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
install-dist_docDATA: $(dist_doc_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(docdir)" || $(MKDIR_P) "$(DESTDIR)$(docdir)"
	@list='$(dist_doc_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(dist_docDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(docdir)/$$f'"; \
	  $(dist_docDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(docdir)/$$f"; \
	done

uninstall-dist_docDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_doc_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(docdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(docdir)/$$f"; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -755 -exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(DATA) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(docdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-rm -f bcftools_src/$(DEPDIR)/$(am__dirstamp)
	-rm -f bcftools_src/$(am__dirstamp)
	-rm -f pbgzip_src/$(DEPDIR)/$(am__dirstamp)
	-rm -f pbgzip_src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-libLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR) bcftools_src/$(DEPDIR) pbgzip_src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

info: info-recursive

info-am:

install-data-am: install-dist_docDATA

install-dvi: install-dvi-recursive

install-exec-am: install-binPROGRAMS install-libLIBRARIES

install-html: install-html-recursive

install-info: install-info-recursive

install-man:

install-pdf: install-pdf-recursive

install-ps: install-ps-recursive

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR) bcftools_src/$(DEPDIR) pbgzip_src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dist_docDATA \
	uninstall-libLIBRARIES

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) install-am \
	install-strip

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-binPROGRAMS \
	clean-generic clean-libLIBRARIES clean-libtool ctags \
	ctags-recursive dist dist-all dist-bzip2 dist-gzip dist-shar \
	dist-tarZ dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am \
	install-dist_docDATA install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-libLIBRARIES install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs installdirs-am \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags tags-recursive uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-dist_docDATA \
	uninstall-libLIBRARIES

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
